# Generated by Django 4.2.2 on 2023-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=265)),
                ('second_name', models.CharField(max_length=265)),
                ('phone', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
